# Generated by Django 4.2.1 on 2023-05-18 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(db_column='CategoryId', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=200)),
                ('symbol', models.CharField(db_column='Symbol', max_length=20)),
                ('agemin', models.IntegerField(blank=True, db_column='AgeMin', null=True)),
                ('agemax', models.IntegerField(blank=True, db_column='AgeMax', null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('clubid', models.AutoField(db_column='ClubId', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=200)),
                ('location', models.CharField(db_column='Location', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('competitorid', models.AutoField(db_column='CompetitorId', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=200)),
                ('surname', models.CharField(db_column='Surname', max_length=200)),
                ('gender', models.CharField(db_column='Gender', max_length=1)),
                ('jmbg', models.CharField(db_column='JMBG', max_length=13)),
                ('dateofbirth', models.DateTimeField(db_column='DateOfBirth')),
                ('categoryid', models.IntegerField(db_column='CategoryId')),
                ('totalpoints', models.IntegerField(blank=True, db_column='TotalPoints', null=True)),
                ('clubid', models.IntegerField(blank=True, db_column='ClubId', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('place', models.IntegerField(blank=True, db_column='Place', null=True)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
                ('pointsid', models.AutoField(db_column='PointsID', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('routeid', models.AutoField(db_column='RouteId', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=200, null=True)),
                ('routesetter', models.CharField(blank=True, db_column='Routesetter', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='UserId', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=200)),
                ('password', models.CharField(db_column='Password', max_length=200)),
                ('name', models.CharField(db_column='Name', max_length=200)),
                ('surname', models.CharField(db_column='Surname', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('userid', models.OneToOneField(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ClimbaseApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('userid', models.OneToOneField(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ClimbaseApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('competitorid', models.IntegerField(db_column='CompetitorId', primary_key=True, serialize=False)),
                ('competitionid', models.IntegerField(db_column='CompetitionId')),
                ('routeid', models.IntegerField(db_column='RouteId')),
                ('zone', models.IntegerField(blank=True, db_column='Zone', null=True)),
                ('zoneattempts', models.IntegerField(blank=True, db_column='ZoneAttempts', null=True)),
                ('top', models.IntegerField(blank=True, db_column='Top', null=True)),
                ('topattempts', models.IntegerField(blank=True, db_column='TopAttempts', null=True)),
                ('judgeid', models.IntegerField(db_column='JudgeId')),
            ],
            options={
                'unique_together': {('competitorid', 'routeid', 'competitionid')},
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('userid', models.OneToOneField(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ClimbaseApp.user')),
                ('clubid', models.ForeignKey(blank=True, db_column='ClubId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ClimbaseApp.club')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('competitionid', models.AutoField(db_column='CompetitionId', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=1, null=True)),
                ('categoryid', models.ForeignKey(blank=True, db_column='CategoryId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ClimbaseApp.category')),
                ('userid', models.ForeignKey(blank=True, db_column='UserId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ClimbaseApp.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='Judged',
            fields=[
                ('competitionid', models.OneToOneField(db_column='CompetitionId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ClimbaseApp.competition')),
                ('userid', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, to='ClimbaseApp.judge')),
            ],
            options={
                'unique_together': {('competitionid', 'userid')},
            },
        ),
        migrations.CreateModel(
            name='Isincompetition',
            fields=[
                ('routeid', models.OneToOneField(db_column='RouteId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ClimbaseApp.route')),
                ('competitionid', models.ForeignKey(db_column='CompetitionId', on_delete=django.db.models.deletion.DO_NOTHING, to='ClimbaseApp.competition')),
            ],
            options={
                'unique_together': {('routeid', 'competitionid')},
            },
        ),
        migrations.CreateModel(
            name='Competed',
            fields=[
                ('competitorid', models.OneToOneField(db_column='CompetitorId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ClimbaseApp.competitor')),
                ('placement', models.IntegerField(blank=True, db_column='Placement', null=True)),
                ('competitionid', models.ForeignKey(db_column='CompetitionId', on_delete=django.db.models.deletion.DO_NOTHING, to='ClimbaseApp.competition')),
            ],
            options={
                'unique_together': {('competitorid', 'competitionid')},
            },
        ),
    ]
